name: challenge

on: push

jobs: 

        job1:
                name: First Job
                runs-on: ubuntu-latest 
                steps: 
                 - name: step 1
                 - run: date
        job2:
                name: Second Job
                runs-on: windows-latest
                steps:
                 - name: step 2
                 - run: Get-Date

        job3:
                name: Third Job
                runs-on: macos-latest
                steps: 
                 - name: step 3
                 - run: date
        job4: 
                name: Fourth Job
                runs-on: ubuntu-18.04
                needs: [job1, job2, job3]
                steps:
                 - name: step 4 conditional
                 - run: date
